authors = ["Velimir (monty) Vesselinov", "Boian Alexandrov", "Vesselin Grantcharov", "Daniel O'Malley"]
name = "SVR"
uuid = "3c50dbde-abaf-11e8-211a-656f602baacb"
version = "0.3.1"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DocumentFunction = "5593b220-aad2-11e8-0680-d9fc7de3193b"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
