name = "SVR"
uuid = "22bb73d7-edb2-5785-ba1e-7d60d6824784"
version = "0.8.2"

[deps]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
DocumentFunction = "e1f3b4f0-2dc4-57d3-83f7-d4b7faf3b05b"
Libdl = "8f399da3-3557-5675-b5ff-fb832c97cbdb"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
DocumentFunction = "^0"
julia = "^1.4"

[extras]
DelimitedFiles = "8bb1440f-4735-579b-a4ab-409b98df4dab"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["DelimitedFiles", "Test"]
